### ISSUE TITLE
[Bug]: OpenAI-compatable providers no longer working on agent-canvas 1.20.0

### ISSUE THREAD

**Issue by Blaze147** [OpenHands/software-agent-sdk#5191]
### Is there an existing issue for the same bug?

- [x] I have searched existing issues and this is not a duplicate.

### Bug Description

After upgrading to @openhands/agent-canvas@1.20.0 today, any run utilizing an OpenAI-compatable API gateway provider that natively handles server-side prompt caching (such as DeepInfra in my case) immediately crashes with an Attribute Error.

Exact error message:
`AttributeError: 'PromptTokensDetailsWrapper' object has no attribute 'cache_creation_tokens'`

Image is attached.

### Actual Behavior

The thread conversation/agent fails immediately upon sending the first prompt. The UI throws an exception message (AttributeError: 'PromptTokensDetailsWrapper' object has no attribute 'cache_creation_tokens') and the session halts. The application does not crash, but these requests to an OpenAI-compatable provider fail.

### Steps to Reproduce

Make a request using an OpenAI-compatable provider

### Acceptance Criteria

Compatibility preservation.... Ideally this failure should not occur and the chat should be allowed to continue.

### Version Confirmation

- [ ] I have confirmed this bug exists on the LATEST version of OpenHands SDK

### Operating System

None
